### ISSUE TITLE
White screen when run the app

### ISSUE THREAD

**Issue by m4tt86** [krushkamx/nativescript-hprt-demo#1]
Hello,
if I run the app on my ios device it show me a white screen where I wrong?
In my console I read this:

`CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1052:24: ERROR Error: Uncaught (in promise): TypeError: undefined is not a constructor (evaluating 'new nativescript_hprt_1.Hprt()')`

**Comment by davorpeic** [comment]
Hi Daniele, this plugin is made at this moment for android only.

**Comment by m4tt86** [comment]
ok, thank you. When are you going to release the ios version?
